### ISSUE TITLE
Two factor authentication 

### ISSUE THREAD

**Issue by ekjuanrejon** [Aguafrommars/TheIdServer#1012]
Is two factor authentication sign-in supported? Like using Microsoft app authenticator?

**Comment by aguacongas** [comment]
Yes it is. And you can [configure the 2fa authenticator issuer](https://github.com/Aguafrommars/TheIdServer/blob/master/src/Aguacongas.TheIdServer.Duende/README.md#configure-the-2fa-authenticator-issuer)
