### ISSUE TITLE
Failed to run as a self-contained app in Aguacongas.TheIdServer project

### ISSUE THREAD

**Issue by anjanasagathiya** [Aguafrommars/TheIdServer#1049]
I am trying to build and run this repository in my local machine. So it is built successfully in my machine but when I am trying to run the application I am getting this error.

A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\AdminUI\TheIdServer\src\Aguacongas.TheIdServer\bin\Debug\net7.0\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'D:\AdminUI\TheIdServer\src\Aguacongas.TheIdServer\bin\Debug\net7.0\Aguacongas.TheIdServer.runtimeconfig.json' was not found.

I have tried to clean and rebuild the solution but it is not resolved. FYI, I have set the below project as start up projects

1. Aguacongas.TheIdServer
2. Aguacongas.TheIdServer.BlazorApp
3. Aguacongas.TheIdServer.Duende

Can you please help me to resolve this issue?

**Comment by aguacongas** [comment]
Hi, thx to contribute. 

You just need to start _Aguacongas.TheIdServer.Duende_, check the launchSettings.json to start the project on port 5443 for HTTPS.
_Aguacongas.TheIdServer_ cannot be started it's a lib.  
_Aguacongas.TheIdServer.BlazorApp_ can be started but it's not configured by default. The app is hosted in _Aguacongas.TheIdServer.Duende_.

**Comment by anjanasagathiya** [comment]
@aguacongas Have you any steps to run the whole application?I have connected the my local database successfully and start only  Aguacongas.TheIdServer.Duende but still I am not able to run application. Also , I am trying to connect with my existing duende server but don't know where I need to provide the the identity server URL? Can you please help me in it?

**Comment by ekjuanrejon** [comment]
can be Aguacongas.TheIdServer.BlazorApp disabled from load in duende and only have duende enabled? Aguacongas.TheIdServer.BlazorApp i want it to be private..?

is it possible?

**Comment by aguacongas** [comment]
@ekjuanrejon. Use the MultiTiers sample then
