### ISSUE TITLE
Unresolved services in API project. 

### ISSUE THREAD

**Issue by scharada** [Aguafrommars/TheIdServer#1075]
hello, have compiled the solution code using VS 2022 IDE.
i have started the Aguacongas.TheIdServer.Duende project which tries to connect to the API running on port 5443. i believe it is the  Aguacongas.TheIdServer.Public project.

the API project throws the exception below. it is looking for a service which is not registered (i verified that). am i missing something ? 

System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Aguacongas.IdentityServer.Store.IExternalProviderKindStore Lifetime: Transient ImplementationType: Aguacongas.IdentityServer.Store.ExternalProviderKindStore`1[Aguacongas.TheIdServer.Authentication.SchemeDefinition]': Unable to resolve service for type 'Aguacongas.AspNetCore.Authentication.IAuthenticationSchemeOptionsSerializer' while attempting to activate 'Aguacongas.IdentityServer.Store.ExternalProviderKindStore`1[Aguacongas.TheIdServer.Authentication.SchemeDefinition]'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build() in Microsoft.AspNetCore.Builder\WebApplicationBuilder.cs:line 85
   at Program.<Main>$(String[] args) in D:\Identity\TheIdServer\sample\MultiTiers\Aguacongas.TheIdServer.Public\Program.cs:line 13

  This exception was originally thrown at this call stack:
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, System.Reflection.ParameterInfo[], bool)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache, System.Type, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, int)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(Microsoft.Extensions.DependencyInjection.ServiceDescriptor)

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Aguacongas.IdentityServer.Store.IExternalProviderKindStore Lifetime: Transient ImplementationType: Aguacongas.IdentityServer.Store.ExternalProviderKindStore`1[Aguacongas.TheIdServer.Authentication.SchemeDefinition]': Unable to resolve service for type 'Aguacongas.AspNetCore.Authentication.IAuthenticationSchemeOptionsSerializer' while attempting to activate 'Aguacongas.IdentityServer.Store.ExternalProviderKindStore`1[Aguacongas.TheIdServer.Authentication.SchemeDefinition]'.

Inner Exception 2:
InvalidOperationException: Unable to resolve service for type 'Aguacongas.AspNetCore.Authentication.IAuthenticationSchemeOptionsSerializer' while attempting to activate 'Aguacongas.IdentityServer.Store.ExternalProviderKindStore`1[Aguacongas.TheIdServer.Authentication.SchemeDefinition]'.

awesome work and thank you for your help.

just a hint: it would be nice to have a readme explaining the role of each of the projects in the solution and maybe the best practice to use them for custom scenarios such as microservices with gateway...

**Comment by scharada** [comment]
thank you very much for your fast reply. it works like a charm.
my wish is to run the API and the admin app separately. 
i also need to create an api gateway for a number of microservices, each must authenticate and authorize against  theidserver.
the solution will have several client apps (mobile, web and windows)... they communicate with the microservices through the gateway.
all must be secured through theidserver.
would you please point me to the right directions or the right samples to learn from ?
thank you

**Comment by aguacongas** [comment]
You already have samples in the default configuration. You just need to add your clients, api, scopes, identity resources depending on your needs.  

The default configuration contains:  
* User
  - The default admin user (You should create a new one)
* Roles
  - Is4-Writer giving access for writing to the TheIdServer api
  - Is4-Reader giving access for reading to the TheIdServer api
* Clients
  - The admin app using the [authorization code flow](https://auth0.com/docs/authenticate/login/oidc-conformant-authentication/oidc-adoption-auth-code-flow)
  - The public server (you probably don't need it) using the [client credential flow](https://auth0.com/docs/authenticate/login/oidc-conformant-authentication/oidc-adoption-client-credentials-flow)
  - The swagger client (You should disable it in production) using the [implicit flow](https://auth0.com/docs/authenticate/login/oidc-conformant-authentication/oidc-adoption-implicit-flow)
* Api
  - The TheIdServer api used by the admin app, public server, and swagger client
* Scopes
  - The api scope
  - The token scope
* Identities resources
  - OpenId/Connect default identities resources

The [sample directory](https://github.com/Aguafrommars/TheIdServer/tree/master/sample) contains a sample for each kind of application.
