### ISSUE TITLE
Blazor app spinning

### ISSUE THREAD

**Issue by ekjuanrejon** [Aguafrommars/TheIdServer#1170]
![image](https://github.com/Aguafrommars/TheIdServer/assets/38057696/ab7cbbde-dc50-4fa8-90f3-ac01f30b6f11)

**Comment by aguacongas** [comment]
Start the project src/Aguacongas.TheIdServer.Duende using VS

**Comment by ekjuanrejon** [comment]
and how can i change the variables for the blazor app when using src/Aguacongas.TheIdServer.Duende ?

**Comment by ekjuanrejon** [comment]
do i have to fork it?

**Comment by ekjuanrejon** [comment]
do you have a docker-compose.yaml?

**Comment by aguacongas** [comment]
No
