### ISSUE TITLE
How To Use TheIdServer without Asp.Net Core Identity framework. 

### ISSUE THREAD

**Issue by umar-ulabs** [Aguafrommars/TheIdServer#1172]
I already have Asp.Net Core Identity framework in use for the application. I dont want to touch its related tables(AspNetuser,AspNetRoles and so on), I have a separate table called  ManufacturingUser. It has nothing to do with Identity framework/UserManager. How would I go about using TheIdServer just for these set of users? or is it even possible. Thank you

**Comment by aguacongas** [comment]
You can create a [custom claims providers](https://github.com/Aguafrommars/TheIdServer/blob/master/doc/CLAIMS_PROVIDER.md) adding a claim of your choice when the user is present in table ManufacturingUser. 
Then your apps and your protected resources can check for this claim and alloy or not the access.
