### ISSUE TITLE
Only 10 entities are visible on the admin UI lists

### ISSUE THREAD

**Issue by AnKa0** [Aguafrommars/TheIdServer#1243]
**Describe the bug**
On the admin UI, if we have more than 10 entities of a kind (clients, users, roles, etc...), only the first 10 show up on the corresponding pages. The remaining ones are not displayed therefore can not be viewed and edited through the UI.

**To Reproduce**
1. Add at least 11 entities of one kind (for example clients)
2. Open the _clients_ page and see that  the 11th one is not displayed there

**Expected behavior**
Please either implement pagination (I can see that it's built in the models but missing from the views) or at least increase the page size as a quick fix

**Comment by aguacongas** [comment]
as a workaround you can filter lists

**Comment by EversongWoods** [comment]
#1274 @aguacongas
