### ISSUE TITLE
Unable to login due to timezone/UTC offset mismatch when using PostgreSQL as the database provider

### ISSUE THREAD

**Issue by GotterMoney** [Aguafrommars/TheIdServer#1309]
**Describe the bug**
Unable to login due to timezone/UTC offset mismatch when using PostgreSQL as the database provider. The system throws an ArgumentException related to UTC offset not matching the offset parameter when attempting to login.

**To Reproduce**
1. Configure `appsettings.json` to use PostgreSQL:
   - Set `DbType` to "PostgreSQL"
   - Update connection string to PostgreSQL format
2. Start the application
3. Navigate to login page
4. Enter credentials
5. Click login button
6. System fails to complete login process

**Expected behavior**
User should be able to successfully log in regardless of timezone settings or database provider choice.

**Logs**
```
System.ArgumentException: The UTC Offset of the local dateTime parameter does not match the offset argument. (Parameter 'offset')
   at System.DateTimeOffset..ctor(DateTime dateTime, TimeSpan offset)
   at Duende.IdentityServer.Extensions.AuthenticationTicketExtensions.Deserialize(ServerSideSession session, IDataProtector protector, ILogger logger) in /_/src/IdentityServer/Extensions/AuthenticationTicketExtensions.cs:line 148
```

**Platform**
- OS: Windows
- .NET Core Version: 8.0

**Additional context**
The issue appears to be related to how datetime values are stored and retrieved from PostgreSQL, specifically affecting the authentication ticket deserialization process. This only occurs when using PostgreSQL as the database provider, suggesting a potential timezone handling discrepancy between the application and the database server.

The error indicates that there's a mismatch between the DateTime's UTC offset and the expected offset during the session deserialization process. This could be caused by how PostgreSQL handles timestamp with timezone information compared to other database providers.

**Comment by aguacongas** [comment]
Hi, Thx a lot to contribute. This issue is fixed in [8.2.1](https://github.com/Aguafrommars/TheIdServer/releases/tag/8.2.1)
