### ISSUE TITLE
Auth type mismatch in example project

### ISSUE THREAD

**Issue by ben-jacobs** [Aguafrommars/TheIdServer#388]
Hi, in the server project with default configuration - authenticating in the Swagger UI (OAuth) and running examples that require authentication do not work. I believe this is because the token type for the swagger client is Jwt, whereas the rest of the example uses ReferenceTokens.

Changing the AccessTokenType to Reference fixes the issue and the API works correctly.

It'd be good if the example project could be configured to use Jwt for the API endpoint to show mixed use scenarios.

Cheers,

Ben

**Comment by aguacongas** [comment]
@ben-jacobs can you test the resolution on branch [fix/jwt-audience](../tree/fix/jwt-audience) and tell me ?

**Comment by ben-jacobs** [comment]
Thanks for coming back so quickly. PS Great project - setting up IdSrv can be a bit of an hassle and you've made it so much easier.

Presumably line 346 needs: return Task.CompletedTask; otherwise context.Token just gets overridden if it is actually using a OTK.

I've added that line in for now and it all appears to be working following the change.

Now all the project needs is a RavenDB backing store and a SAML/Okta provider and it'll be perfect ;)

**Comment by aguacongas** [comment]
RavenDB stores are on the way [feature/ravendb](../tree/feature/ravendb).  
Okta is an OIDC provider so you can add it using OpenIdConnect.
Open a new enhancement if you need a SAML provider ;-)
