### ISSUE TITLE
Clients with multiple RedirectUris do not have CORS flag set correctly

### ISSUE THREAD

**Issue by ben-jacobs** [Aguafrommars/TheIdServer#395]
Apologies for bad format of this bug report - just under a bit of time pressure.

When there is more than one RedirectUri for a client, the CORS flag is not being set correctly.
This is because in Aguacongas.IdentityServer.Store.EntityExtensions, the public static Entity.Client ToEntity(this Client client) uses a FirstOrDefault match against the AllowedCors list. Changing this to a foreach loop with Where fixes this issue (I think).

  ```
foreach (var origin in client.AllowedCorsOrigins)
            {
                var cors = new Uri(origin);
                **foreach (var uri in uris.Where(u => cors.CorsMatch(u.Uri)))**
                {
```

Cheers,

Ben

**Comment by aguacongas** [comment]
@ben-jacobs Thanks to contribute. Are you sure you flags your Uris with CORS :

![image](https://user-images.githubusercontent.com/3294829/112943242-883c2480-9131-11eb-91db-27df5e7a1e05.png)

It works with *theidserveradmin* client so I don't think it's the issue

**Comment by ben-jacobs** [comment]
But not multiple uris with the same host - it'll only flag the first one.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aguacongas** [comment]
CORS only check scheme and host, not the path, that should not be an issue. So, just flag one host

**Comment by ben-jacobs** [comment]
The issue is not with how CORS works per se - just that multiple URIs with the same host don't all get the flag set and this creates errors when calling etc. This is an issue for example when using multiple oidc within the one app - to support persistent logins v. full logins. I was previously logging into the admin interface and setting the CORS flag on the additional URIs, but the foreach fixed the issue - I'll just keep it in my local branch if you're not convinced.

**Comment by aguacongas** [comment]
So, if you fixed it, can you create a PR ?
