### ISSUE TITLE
Incorporate AspNetCore.Diagnostics.HealthChecks

### ISSUE THREAD

**Issue by ben-jacobs** [Aguafrommars/TheIdServer#423]
What are you thoughts on incorporating AspNetCore.Diagnostics.HealthChecks into Aguacongas.TheIdServer? 

In the first instance this could be as simple as adding a healthcheck to ensure the IdSrv discovery endpoints are available - with enhancements covering the DB providers etc if necessary. In this most basic configuration, it shouldn't add more than a few lines of configuration code - there's even an IdentityServer healthcheck already available.

Given that I think the project is very conducive to being part of a microservices architecture, the healthchecks would allow for common orchestration tools to check the health status.

**Comment by aguacongas** [comment]
I agree it's missing. Do you wanna implement it ?<

**Comment by ben-jacobs** [comment]
Happy to make a start - the IdSrv4 check should be straight forward.

Database checks should be OK, just a lot of boilerplate for the different supported types. But we can maybe avoid the above by just checking the api and watching for a specific exception type (does it throw a consistent exception if the dB is unavailable when the api is called?) The auth to call the APIs in this case will be the tricky bit (in theory the user can delete the client in the ui and then health checks would fail, even though they'd actually be working fine for the user auth.

Health checks for external providers is probably the most complex and arguably less relevant to Theidserver health (can't guarantee network availability for oauth dance at the user end etc - most things are out of your control).

Probably a week or so before I start, been sick and a few things to catch up on first.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aguacongas** [comment]
Health check implemented in [4.5.0](https://github.com/Aguafrommars/TheIdServer/releases/tag/4.5.0).  Doc [here](https://github.com/Aguafrommars/TheIdServer/tree/4.5.0/src/Aguacongas.TheIdServer.Duende#health-checks)
