### ISSUE TITLE
On mobile devices Register and Login links are not visible

### ISSUE THREAD

**Issue by ben-jacobs** [Aguafrommars/TheIdServer#424]
On mobile devices (or when compact nav layout is active) Register and Login links are not visible (ie cannot login)

**Comment by aguacongas** [comment]
You can still login actually, just click on a menu item. But. I agree, you cannot register or logout

**Comment by ben-jacobs** [comment]
It's not a huge deal - only impacts a relatively small group of admin users, not people authenticating against the IdSrv. 

Maybe just move those links (register, login, logout and the IdSrv profile link/user) to the top of the side menu?

**Comment by aguacongas** [comment]
Yeah, I'm hesitate between top or bottom actually

**Comment by ben-jacobs** [comment]
Logout at the bottom is common but Register and Login should probably be at the top, with the other menu items hidden until authenticated would be preferable if that's possible? I always find it a bit weird seeing menu items before logging in - particularly if restricted by a role/claim.

**Comment by aguacongas** [comment]
![image](https://user-images.githubusercontent.com/3294829/114199495-a5080180-9954-11eb-9f6f-8e53e0fdf4f5.png)![image](https://user-images.githubusercontent.com/3294829/114199638-c49f2a00-9954-11eb-940a-e54629c0cbd3.png)
![image](https://user-images.githubusercontent.com/3294829/114201009-10060800-9956-11eb-9631-c3ad98f93193.png)
