### ISSUE TITLE
OData exception (RavenDB)

### ISSUE THREAD

**Issue by ben-jacobs** [Aguafrommars/TheIdServer#437]
Howdy :)

Pretty sure that And has to be and .... otherwise there's a syntax error thrown by OData.

GrantStore.cs
```
 protected virtual async Task<TEntity> GetEntityBySubjectAndClient(string subjectId, string clientId)
        {
            return (await _store.GetAsync(new PageRequest
            {
                Filter = $"{nameof(UserConsent.UserId)} eq '{subjectId}' **and** {nameof(UserConsent.ClientId)} eq '{clientId}'"
            }).ConfigureAwait(false)).Items.FirstOrDefault();
        }
```

**Comment by aguacongas** [comment]
This method is under unit test through : [UserConsentStoreTest.GetUserConsentAsync_should_call_store_GetAsync](https://github.com/Aguafrommars/TheIdServer/blob/feature/mongodb/test/Aguacongas.IdentityServer.Http.Store.Test/UserConsentStoreTest.cs) and it doesn't throw. But, for coherence, I'll lowered case **And**

**Comment by ben-jacobs** [comment]
Haven't looked at the unit tests - but was definitely throwing with "And" and doesn't throw with "and" ... at least when using the RavenDB driver. 

Have been away and just catching up with all the changes. Excellent progress! The library/app is definitely coming together nicely!
