### ISSUE TITLE
Please explain: How to solve the following problems? thank you very much!

### ISSUE THREAD

**Issue by Line4GitHub** [Aguafrommars/TheIdServer#578]
Please explain:
How to solve the following problems? 
--------------
While run TheIdServer Admin (Aguacongas.TheIdServer.IS4) on localhost:44382,
An unhandled exception has occurred. See browser dev tools for details.
--------------
Failed to load resource: net::ERR_CONNECTION_REFUSED
:5443/api/culture?orderby=Id&select=Id:1 
:5443/api/localizedresource?orderby=CultureId&filter=CultureId%20eq%20%27zh-TW%27%20or%20CultureId%20eq%20%27zh-Hant%27:1
:5443/.well-known/openid-configuration:1 
:5443/api/culture?orderby=Id&select=Id:1
:5443/api/welcomefragment?culture=zh-TW:1
--------------
Then after click Login
--------------
localhost:44382/authentication/login-failed
Authentication
There was an error trying to log you in: 'Network Error'
--------------
thank you very much!
--------------

**Comment by aguacongas** [comment]
Check the BlazorApp [*appsettings.json* file in *wwroot*](https://github.com/Aguafrommars/TheIdServer/blob/master/src/Aguacongas.TheIdServer.BlazorApp/wwwroot/appsettings.json), URLs point to localhost:5443 so either run the server on 5443 or update admin app settings.

**Comment by Line4GitHub** [comment]
Thank you very much!
