### ISSUE TITLE
Great project. Can sharepoint2013 be used?

### ISSUE THREAD

**Issue by sibo-git** [Aguafrommars/TheIdServer#726]
The certificate cannot be saved. After clicking save, the database does not store data?

I don't know much. Doesn't the certificate need a private key?

**Comment by aguacongas** [comment]
Can you be more explicit, I don't get your question. 
- What for you use sharepoint ? As an external provider ?
- Which certificate your are talking about ?
- Where do you click save ?

**Comment by aguacongas** [comment]
I guess you're talking about encryption certificate in relying party page. And, yes, they was an issue saving the certificate, PR #727 fix it.
The encryption certificate must be a valid certificate:
* If it is, the page display is thumbprint. 
![image](https://user-images.githubusercontent.com/3294829/164510107-aae273f9-273d-4c44-934a-9e10e2c125a3.png)

* If not, the error is displayed
![image](https://user-images.githubusercontent.com/3294829/164510288-fe94ced1-2c63-4c34-ab70-2b26fa0aaf70.png)

**Comment by sibo-git** [comment]
I was too busy yesterday and didn't reply to you. That's great.
