### ISSUE TITLE
Facebook Provider problem

### ISSUE THREAD

**Issue by bulente** [Aguafrommars/TheIdServer#780]
Local logins work without a problem. I tried to add facebook provider. 

Pressing Facebook button at /account/login page redirects to facebook and after successful authentication, it returns to my authority server with an url like this:

https://myserver/?code=somecode&state=somestate

and this page gives a 404 error without returning to the calling client page. 

I tried almost any option in the provider setup page. My last configuration is like this:

![image](https://user-images.githubusercontent.com/31597833/169548857-8308860e-3eb9-442a-8536-a0e1ee74e1fe.png)

**Comment by aguacongas** [comment]
The callback url configured on facebook should end with /signin-{providerId} for exemple [https://myserver/signin-facebook](https://myserver/signin-facebook)

**Comment by bulente** [comment]
I tried /signin-facebook also. When it is like that, after successful login within facebook, it returns to my server like this:

https://myserver/signin-facebook?code=somecode&state=somestate and that page shows a 404 error without redirecting to calling client page. 

![image](https://user-images.githubusercontent.com/31597833/169570773-c90a4436-3027-4a03-807e-1d9adb418ef4.png)

**Comment by aguacongas** [comment]
And your provider id is facebook right ? Put the log in debug mode and share it please.

**Comment by bulente** [comment]
Yes:
![image](https://user-images.githubusercontent.com/31597833/169574307-394c35dc-5971-4cb6-80bf-802fb72cf48e.png)

How to put the log in debug mode?

**Comment by aguacongas** [comment]
in the appsettings.json :

```json
"Serilog": {
    "LevelSwitches": {
      "$controlSwitch": "Debug"
    },
```

**Comment by bulente** [comment]
![image](https://user-images.githubusercontent.com/31597833/169582255-ac8834c8-aabe-4b89-9ccc-80fca538b180.png)

**Comment by bulente** [comment]
![image](https://user-images.githubusercontent.com/31597833/169582447-051a36e2-3fc8-4683-a19d-c6a6e96240ba.png)

**Comment by aguacongas** [comment]
Do you see the 404 in logs ?

**Comment by bulente** [comment]
No log containing 404 text. 

The 302 responded page gives the 404 error:

https://auth.bebyaz.com/External/Challenge?provider=facebook&returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dtheidserveradmin%26redirect_uri%3Dhttps%253A%252F%252Fauth.bebyaz.com%252Fauthentication%252Flogin-callback%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520openid%2520profile%2520theidserveradminapi%26state%3D59363698e69c4a5ca1bcc50d474eabfd%26code_challenge%3Dau1VNsUJ4unfM0SS77szPXyHUFC9lPt25uQJ7d9qClY%26code_challenge_method%3DS256%26response_mode%3Dquery

you can also try it with this url:
https://auth.bebyaz.com/account/login

**Comment by bulente** [comment]
The problem was fixed. I added these to the appsettings.json:

"CustomEntriesOfStringArray": {
      "token_endpoint_auth_signing_alg_values_supported": [
        "RS256",
        "ES256",
        "ES384",
        "ES512",
        "PS256",
        "PS384",
        "PS512",
        "RS384",
        "RS512"
      ]

"AdditionalSigningKeyType": {
        "RS384": {
          "SigningAlgorithm": "RS384"
        },
        "RS512": {
          "SigningAlgorithm": "RS512"
        },
        "PS256": {
          "SigningAlgorithm": "PS256"
        },
        "PS384": {
          "SigningAlgorithm": "PS384"
        },
        "PS512": {
          "SigningAlgorithm": "PS512"
        },
        "ES256": {
          "SigningAlgorithm": "ES256"
        },
        "ES384": {
          "SigningAlgorithm": "ES384"
        },
        "ES512": {
          "SigningAlgorithm": "ES512"
        }
      }

**Comment by bulente** [comment]
No 404 in logs. Now when I pressed the Facebook button within the Admin UI application, it works. But if the login page is a result of an OWIN client request. It doesn't returns to that client and shows 404 page. Local Login works for that Owin client.

**Comment by aguacongas** [comment]
I guess the host is wrong then, double check it, it's looks like it do not return to your TheIdServer instance. The callback url should callback your identity server. Then the identity server callback to the app.

**Comment by bulente** [comment]
404 error is showing in TheIdServer URL page. Which callback setting do you mean? I'm try to implement this logic to an old ASP.NET MVC 4 application and here is my owin startup code:

JwtSecurityTokenHandler.DefaultInboundClaimTypeMap = new Dictionary<string, string>();

app.UseCookieAuthentication(new CookieAuthenticationOptions
{
AuthenticationType = "Cookies"
});



app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
AuthenticationType = "oidc",
UsePkce = true,
ClientId = myclientid,
ClientSecret = myclientsecret,
Authority = mytheidserver,


#if DEBUG
RedirectUri = "https://localhost:44326",
#else
RedirectUri = my web client,
#endif


ResponseType = "id_token",
//ResponseType = "code",
//ResponseMode = "query",
Scope = "openid email",

UseTokenLifetime = false,
SignInAsAuthenticationType = "Cookies",
SaveTokens = true,

});

**Comment by aguacongas** [comment]
On [Facebook Developers app](https://developers.facebook.com/apps/) you need to provide the redirect URI for your client, this is the callback url. In this case the client is your TheIdServer, facebook should redirect to your TheIdServer instance not to your MVC client directly. As you don't see a 404 entry in your TheIdServer log, it means the callback do not return to your TheIdServer instance, do you agree ? If it was redirected to an unknown page of TheIdServer, the admin app should display: 

![image](https://user-images.githubusercontent.com/3294829/169654778-abdfb5e3-d6e5-49f4-a0ac-42d7ccbb29d0.png)

**Comment by bulente** [comment]
I don't know why the 404 error isn't showing in the logs. I took a snapshot of the flow with burp proxy. domain starting with auth is my idserver and domain staring with batu is my mvc client:

![image](https://user-images.githubusercontent.com/31597833/169658565-8f2bc2e6-6937-4231-b024-a95489b5c153.png)

**Comment by bulente** [comment]
Here is my Provider latest setup:

![image](https://user-images.githubusercontent.com/31597833/169659526-5fc79f79-3690-4047-83bc-de84a4ac39ed.png)

**Comment by bulente** [comment]
And my client setup:

![image](https://user-images.githubusercontent.com/31597833/169659583-7471a237-d56a-46e6-83a4-b1b654ec1fe1.png)

**Comment by aguacongas** [comment]
Are you behind a proxy ? If we can not found the 404 request in the log, it's because the request is not processed by TheIdServer, do you agree ?

**Comment by bulente** [comment]
Only one entry containing "signin-facebook" :

![image](https://user-images.githubusercontent.com/31597833/169660160-4c056f3e-a092-4d56-9420-4145d0918676.png)

https://myidserver/signin-facebook?code=somecode&state=somestate

URL gives 404 error. That means the server code can't find a matching route for this URL, isn't it?  When this happens, is there a global error handling routine in the code and does it writes to log?

**Comment by aguacongas** [comment]
And what if you try to login with facebook using TheIdServer admin ?  
What's the TheIdServer version you use ?

if you use SEQ, try to filter logs with : `RequestPath = '/signin-facebook'`

![image](https://user-images.githubusercontent.com/3294829/169663751-29d0ce32-540b-411a-a21c-767aed8d6922.png)

**Comment by aguacongas** [comment]
And your MVC application should use the **Hybrid** grant type, not **Token exchange**, nor **Implicit**, nor **Client credentials**

**Comment by bulente** [comment]
I'm using the latest commits from this repo now. Yesterday I was using the old commits that contain a Duende version of 6.1.0-preview.4"

When I filter the log with requestpath, I'm only seeing the successful logins from TheIdServer admin two days ago:
![image](https://user-images.githubusercontent.com/31597833/169678078-a0f6aa79-d852-4a7e-a148-3e370251bb17.png)

Now I even can't login from TheIdServer admin.  My current settings is like this:
Facebook developer page contains only one redirect url: https://auth.bebyaz.com/signin-facebook

Admin->Provider:  id is "facebook", sign-in path is "/signin-facebook". 
Admin->Client:  id is theidserveradmin, grant type is code. "https://auth.bebyaz.com/signin-facebook" is in the redirect uri list. Scopes contain theidserveradmin, profile, openid and email.

If only I take a snapshot of the settings when I successfully login :( But now I learn a lot in 2 days about oauth, openid, sso..etc and this is the main reason I try to install the system. Thanks for your time and quick responses.

**Comment by aguacongas** [comment]
The *theidserveradmin* redirect uri should be : "[https://auth.bebyaz.com/authentication/login-callback](https://auth.bebyaz.com/authentication/login-callback)" ,"[/signin-facebook](/signin-facebook)" should not be used as redirect path for clients.

Drop the database. it'll recreate at startup. You probably have issue with stored security keys.

**Comment by bulente** [comment]
I found that the IIS was filtering the request because of long query string. Adding this to web.config solved the problem:

<configuration>
  ...
  <system.webServer>
    ...
    <security>
      <requestFiltering>
        <requestLimits maxQueryString="8192" />
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>

Thank you for your support. I learned OAuth, OpenId flows and learning new things is always a joy :)
