### ISSUE TITLE
register and lost password button on login page

### ISSUE THREAD

**Issue by bulente** [Aguafrommars/TheIdServer#790]
How can we show register and lost password buttons on the login page, is there a configuration for this?

**Comment by aguacongas** [comment]
No, there is no config for that and the default login page do not provide those buttons. However, you can add link to the registration page ([/identity/account/register]()) and forgot password page ([/identity/account/forgotpassword]()) on your app.  
Or customize the login  view  ([Views/Account/Login.cshtml]())if you use the code. 
I can also add it in a next release or you can propose a PR if you want to contribute.

**Comment by bulente** [comment]
I added these under the form tag on the page, thanks:

`<div class="row">
    <a href="/identity/account/forgotpassword">@Localizer["Forgot Password"]</a>
    <a href="/identity/account/register">@Localizer["Register"]</a>
</div>`
