### ISSUE TITLE
resetpassword link doesn't work

### ISSUE THREAD

**Issue by bulente** [Aguafrommars/TheIdServer#792]
from /identity/account/forgotpassword action, I received an email with a link to reset the password like this:

https://mydomain.com/?area=Identity&code=Q2ZESjhGV2Q2VnhWRnRsQWgyTm14N1JWNWdjVWhSaE1yZ0VvL0lsVUo1UUR3dEhpQjZvZGYwMmk5UThVTm5BM21hYTEveGIwNElKSWsyd3BHTG93OHJMR3JZZ3lGb0FOSEc2alNCMWhYRXExOEhYZjR2R0hUYkVHd2tNdXp5YnRZeDAyUEZjQi9yWWs0Z0JkcUw2VXBKVDhoWUdqODlkcDUyWXk2ZmJvSCtCbEtUbEtaY013VnVUa3NGOHRMbVE3QmtwcCs5SjZJWWEzcXhheG1mQVdoeGV4VlErcHVrMlQ2cU1wMmZRVGJRa3hrakQ5&page=%2FAccount%2FResetPassword%27

Pressing this link doesn't do anything and lands on the home page of the identity server. 

There is no error code and request to this page returns 200:

![image](https://user-images.githubusercontent.com/31597833/170815091-3b3bcd3b-63a5-49ea-8910-9afaba94acfb.png)

**Comment by aguacongas** [comment]
Actually 2 pages where missing : `ResetPassword.cshtml` and `ResetPasswordConfirmation.cshtml`. `ResendEmailConfirmation.cshtml` was missing too and I add option in `AccountOptions` to display *Forgot your password?*, *Register as a new user* and *Resend email confirmation* links on the login page.

**Comment by bulente** [comment]
Confirm fix. Thanks for the quick update.
